apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-rzv4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/hacbs-release-tests/happy-depl-xcdv-tenant/appstudio/dc-metro-map-rzv4@sha256:845e8b5db44276398fd8f404723a04eef1eeed6d5f27b1f24f08448eea8dbbf9
        name: my-nodejs
        resources: {}
status: {}
